version: '2.1'
services:
  db:
    image: vote-db
    ports:
    - "5984:5984"
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:5984/ || exit 1"]
      interval: 10s
      timeout: 5s
  web:
    image: vote
    ports:
    - "8080:8080"
    environment:
    - hoodie_dbUrl=http://db:5984
    - hoodie_dbUrlUsername=admin
    - hoodie_dbUrlPassword=password
    - hoodie_inMemory=true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
    depends_on:
      db:
        condition: service_healthy